spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlserver.cqtixzdrmccc.us-east-1.rds.amazonaws.com:3306/lanchonete
    username: admin
    password: lanchonete
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true