name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package
        run: mvn package

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          package: '*.jar'
          
      - name: Check Java version
        run: java -version

      - name: Build Maven
        run: mvn clean package
        
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
